<?php
namespace App\Controller;

use Rebet\Routing\Attribute\Channel;
use Rebet\Routing\Controller;

/**
 * Top Controller Class
 *
 * NOTE: This is a sample controller generated by skeleton. Edit or remove it as needed.
 */
#[Channel("web")]
class TopController extends Controller
{
    /**
     * Show the top page.
     *
     * @return string
     */
    public function index()
    {
        return 'Top: index';
    }
}
