language: php
php:
  - 7.1

services:
  - mysql
  - postgresql
  - memcached
  - redis-server

addons:
  postgresql: "9.6"

before_install:
  - pecl channel-update pecl.php.net
  - pecl config-set preferred_state beta
  - echo yes | pecl upgrade apcu
  - phpenv config-add ./tests/travis/php.ini

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - mysql -uroot -e "CREATE DATABASE rebet_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin"
  - psql -c 'CREATE DATABASE rebet_test;' -U postgres

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF php
  