language: php
php:
  - 7.4

services:
  - docker
  - mysql
  - postgresql
  - memcached
  - redis-server

addons:
  hosts:
    - mysql
    - pgsql
    - memcached
    - redis

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.27.4
    - MARIADB_HOST=127.0.0.2

before_install:
  # Install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Add php.ini config
  - phpenv config-add ./tests/travis/php.ini
  # Add mariadb hosts
  - echo "${MARIADB_HOST} mariadb" | sudo tee -a /etc/hosts

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - mysql -u root < .devcontainer/docker/mysql/initdb/001_create_database.sql
  - mysql -u root < .devcontainer/docker/mysql/initdb/002_create_tables.sql
  - psql -U postgres < .devcontainer/docker/pgsql/initdb/001_create_database.sql
  - psql -U postgres < .devcontainer/docker/pgsql/initdb/002_create_tables.sql
  - mkdir -p /tmp/sqlite ; echo ".open /tmp/sqlite/rebet.db" | sqlite3
  - sqlite3 /tmp/sqlite/rebet.db < .devcontainer/docker/workspace/sqlite/initdb/create_tables.sql
  - docker-compose run -d -p ${MARIADB_HOST}:3306:3306 mariadb

script:
  - vendor/bin/phpunit --stop-on-fail --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF php
  