language: php
php:
  - 7.3.24
  - 7.4.12

services:
  - docker
  - mysql
  - postgresql
  - memcached
  - redis-server

addons:
  hosts:
    - mysql
    - pgsql
    - sqlsrv
    - memcached
    - redis

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.27.4
    - MARIADB_HOST=127.0.0.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - phpenv config-add ./tests/travis/php.ini
  - echo "${MARIADB_HOST} mariadb" | sudo tee -a /etc/hosts

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - mysql -u root < docker/mysql/initdb.d/001_create_database.sql
  - mysql -u root < docker/mysql/initdb.d/002_create_tables.sql
  - psql -U postgres < docker/pgsql/initdb.d/001_create_database.sql
  - psql -U postgres < docker/pgsql/initdb.d/002_create_tables.sql
  - mkdir -p /tmp/sqlite ; echo ".open /tmp/sqlite/rebet.db" | sqlite3
  - sqlite3 /tmp/sqlite/rebet.db < docker/sqlite/initdb.d/create_tables.sql
  - docker-compose run -d -p ${MARIADB_HOST}:3306:3306 mariadb
  - docker-compose run -d -p 1433:1433 sqlsrv

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF php
  