language: php
php:
  - 7.3.24
  - 7.4.12

services:
  - mysql
  - postgresql
  - memcached
  - redis-server

addons:
  postgresql: "9.6"
  hosts:
    - mysql
    - pgsql
    - memcached
    - redis

before_install:
  - phpenv config-add ./tests/travis/php.ini

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - mysql -u root < docker/mysql/initdb.d/001_create_database.sql
  - mysql -u root < docker/mysql/initdb.d/002_create_tables.sql
  - psql -U postgres < docker/pgsql/initdb.d/001_create_database.sql
  - psql -U postgres < docker/pgsql/initdb.d/002_create_tables.sql
  - mkdir -p /var/lib/sqlite ; echo ".open /var/lib/sqlite/rebet.db" | sqlite3
  - sqlite3 /var/lib/sqlite/rebet.db < docker/sqlite/initdb.d/create_tables.sql

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF php
  