version: '3'
volumes:
  vendor:
  history:
  work:
  var:
services:
  php:
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
    volumes:
      - .:/rebet
      - vendor:/rebet/vendor
      - history:/rebet/.history
      - work:/rebet/tests/work
      - var:/rebet/tests/app/var
      - ./docker/php/.bashrc:/root/.bashrc
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/20-xdebug.ini:/usr/local/etc/php/conf.d/20-xdebug.ini
    working_dir: /rebet
    tty: true
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mariadb/conf.d:/etc/mysql/conf.d
  pgsql:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./docker/pgsql/initdb.d:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: haeckel      # see https://www.adminer.org/#extras https://github.com/vrana/adminer/tree/master/designs
      ADMINER_PLUGINS: enum-option # see https://www.adminer.org/en/plugins/
    ports:
      - 18080:8080
  memcached:
    image: memcached
  redis:
    image: redis
