#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

//-------------------------------------------------
// Create kernel and initilizing application
//-------------------------------------------------
$kernel = Rebet\Application\App::init(new App\Console\AppCliKernel(new App\AppStructure(__DIR__.'/app/')));

//-------------------------------------------------
// Invoke command and handle action
//-------------------------------------------------
$kernel->handle();

//-------------------------------------------------
// Terminate the application
//-------------------------------------------------
$kernel->terminate();