CREATE DATABASE rebet DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;

CREATE USER rebet IDENTIFIED BY 'rebet';
CREATE USER rebet@localhost IDENTIFIED BY 'rebet';
GRANT ALL PRIVILEGES ON rebet.* TO rebet WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON rebet.* TO rebet@localhost WITH GRANT OPTION;
