[Session]
session.save_path = "/workspace/.devcontainer/docker/var/session"

[intl]
intl.default_locale = "{! $locale !}"

[Date]
date.timezone = "{! $timezone !}"

#{%-- if $cache == 'apcu' -%}
[apcu]
apc.enabled=1
apc.enable_cli=1
#{%-- endif -%}
