<?php

use Rebet\Inflection\Inflector;

return [
    Inflector::class => [
        'plural' => [
            'rules' => [
                ['/(s)tatus$/i', '\1\2tatuses'],
                ['/(quiz)$/i', '\1zes'],
                ['/^(ox)$/i', '\1\2en'],
                ['/([m|l])ouse$/i', '\1ice'],
                ['/(matr|vert|ind)(ix|ex)$/i', '\1ices'],
                ['/(x|ch|ss|sh)$/i', '\1es'],
                ['/([^aeiouy]|qu)y$/i', '\1ies'],
                ['/(hive|gulf)$/i', '\1s'],
                ['/(?:([^f])fe|([lr])f)$/i', '\1\2ves'],
                ['/sis$/i', 'ses'],
                ['/([ti])um$/i', '\1a'],
                ['/(c)riterion$/i', '\1riteria'],
                ['/(p)erson$/i', '\1eople'],
                ['/(m)an$/i', '\1en'],
                ['/(c)hild$/i', '\1hildren'],
                ['/(f)oot$/i', '\1eet'],
                ['/(buffal|her|potat|tomat|volcan)o$/i', '\1\2oes'],
                ['/(alumn|bacill|cact|foc|fung|nucle|radi|stimul|syllab|termin|vir)us$/i', '\1i'],
                ['/us$/i', 'uses'],
                ['/(alias)$/i', '\1es'],
                ['/(analys|ax|cris|test|thes)is$/i', '\1es'],
                ['/s$/', 's'],
                ['/^$/', ''],
                ['/$/', 's'],
            ],
            'uninflected' => [
                '.*[nrlm]ese',
                '.*deer',
                '.*fish',
                '.*measles',
                '.*ois',
                '.*pox',
                '.*sheep',
                'people',
                'cookie',
                'police',
            ],
            'irregular' => [
                'atlas'        => 'atlases',
                'axe'          => 'axes',
                'beef'         => 'beefs',
                'brother'      => 'brothers',
                'cafe'         => 'cafes',
                'chateau'      => 'chateaux',
                'niveau'       => 'niveaux',
                'child'        => 'children',
                'cookie'       => 'cookies',
                'corpus'       => 'corpuses',
                'cow'          => 'cows',
                'criterion'    => 'criteria',
                'curriculum'   => 'curricula',
                'demo'         => 'demos',
                'domino'       => 'dominoes',
                'echo'         => 'echoes',
                'foot'         => 'feet',
                'fungus'       => 'fungi',
                'ganglion'     => 'ganglions',
                'genie'        => 'genies',
                'genus'        => 'genera',
                'goose'        => 'geese',
                'graffito'     => 'graffiti',
                'hippopotamus' => 'hippopotami',
                'hoof'         => 'hoofs',
                'human'        => 'humans',
                'iris'         => 'irises',
                'larva'        => 'larvae',
                'leaf'         => 'leaves',
                'loaf'         => 'loaves',
                'man'          => 'men',
                'medium'       => 'media',
                'memorandum'   => 'memoranda',
                'money'        => 'monies',
                'mongoose'     => 'mongooses',
                'motto'        => 'mottoes',
                'move'         => 'moves',
                'mythos'       => 'mythoi',
                'niche'        => 'niches',
                'nucleus'      => 'nuclei',
                'numen'        => 'numina',
                'occiput'      => 'occiputs',
                'octopus'      => 'octopuses',
                'opus'         => 'opuses',
                'ox'           => 'oxen',
                'passerby'     => 'passersby',
                'penis'        => 'penises',
                'person'       => 'people',
                'plateau'      => 'plateaux',
                'runner-up'    => 'runners-up',
                'sex'          => 'sexes',
                'soliloquy'    => 'soliloquies',
                'son-in-law'   => 'sons-in-law',
                'syllabus'     => 'syllabi',
                'testis'       => 'testes',
                'thief'        => 'thieves',
                'tooth'        => 'teeth',
                'tornado'      => 'tornadoes',
                'trilby'       => 'trilbys',
                'turf'         => 'turfs',
                'valve'        => 'valves',
                'volcano'      => 'volcanoes',
            ],
        ],

        'singular' => [
            'rules' => [
                ['/(s)tatuses$/i', '\1\2tatus'],
                ['/^(.*)(menu)s$/i', '\1\2'],
                ['/(quiz)zes$/i', '\\1'],
                ['/(matr)ices$/i', '\1ix'],
                ['/(vert|ind)ices$/i', '\1ex'],
                ['/^(ox)en/i', '\1'],
                ['/(alias)(es)*$/i', '\1'],
                ['/(buffal|her|potat|tomat|volcan)oes$/i', '\1o'],
                ['/(alumn|bacill|cact|foc|fung|nucle|radi|stimul|syllab|termin|viri?)i$/i', '\1us'],
                ['/([ftw]ax)es/i', '\1'],
                ['/(analys|ax|cris|test|thes)es$/i', '\1is'],
                ['/(shoe|slave)s$/i', '\1'],
                ['/(o)es$/i', '\1'],
                ['/ouses$/', 'ouse'],
                ['/([^a])uses$/', '\1us'],
                ['/([m|l])ice$/i', '\1ouse'],
                ['/(x|ch|ss|sh)es$/i', '\1'],
                ['/(m)ovies$/i', '\1\2ovie'],
                ['/(s)eries$/i', '\1\2eries'],
                ['/([^aeiouy]|qu)ies$/i', '\1y'],
                ['/([lr])ves$/i', '\1f'],
                ['/(tive)s$/i', '\1'],
                ['/(hive)s$/i', '\1'],
                ['/(drive)s$/i', '\1'],
                ['/(dive)s$/i', '\1'],
                ['/(olive)s$/i', '\1'],
                ['/([^fo])ves$/i', '\1fe'],
                ['/(^analy)ses$/i', '\1sis'],
                ['/(analy|diagno|^ba|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$/i', '\1\2sis'],
                ['/(c)riteria$/i', '\1riterion'],
                ['/([ti])a$/i', '\1um'],
                ['/(p)eople$/i', '\1\2erson'],
                ['/(m)en$/i', '\1an'],
                ['/(c)hildren$/i', '\1\2hild'],
                ['/(f)eet$/i', '\1oot'],
                ['/(n)ews$/i', '\1\2ews'],
                ['/eaus$/', 'eau'],
                ['/^(.*us)$/', '\\1'],
                ['/s$/i', ''],
            ],
            'uninflected' => [
                '.*[nrlm]ese',
                '.*deer',
                '.*fish',
                '.*measles',
                '.*ois',
                '.*pox',
                '.*sheep',
                '.*ss',
                'data',
                'police',
                'pants',
                'clothes',
            ],
            'irregular' => [
                'abuses'     => 'abuse',
                'avalanches' => 'avalanche',
                'caches'     => 'cache',
                'criteria'   => 'criterion',
                'curves'     => 'curve',
                'emphases'   => 'emphasis',
                'foes'       => 'foe',
                'geese'      => 'goose',
                'graves'     => 'grave',
                'hoaxes'     => 'hoax',
                'media'      => 'medium',
                'neuroses'   => 'neurosis',
                'waves'      => 'wave',
                'oases'      => 'oasis',
                'valves'     => 'valve',
            ],
        ],

        'uninflected' => [
            '.*?media', 'Amoyese', 'audio', 'bison', 'Borghese', 'bream', 'breeches',
            'britches', 'buffalo', 'cantus', 'carp', 'chassis', 'clippers', 'cod', 'coitus', 'compensation', 'Congoese',
            'contretemps', 'coreopsis', 'corps', 'data', 'debris', 'deer', 'diabetes', 'djinn', 'education', 'eland',
            'elk', 'emoji', 'equipment', 'evidence', 'Faroese', 'feedback', 'fish', 'flounder', 'Foochowese',
            'Furniture', 'furniture', 'gallows', 'Genevese', 'Genoese', 'Gilbertese', 'gold',
            'headquarters', 'herpes', 'hijinks', 'Hottentotese', 'information', 'innings', 'jackanapes', 'jedi',
            'Kiplingese', 'knowledge', 'Kongoese', 'love', 'Lucchese', 'Luggage', 'mackerel', 'Maltese', 'metadata',
            'mews', 'moose', 'mumps', 'Nankingese', 'news', 'nexus', 'Niasese', 'nutrition', 'offspring',
            'Pekingese', 'Piedmontese', 'pincers', 'Pistoiese', 'plankton', 'pliers', 'pokemon', 'police', 'Portuguese',
            'proceedings', 'rabies', 'rain', 'rhinoceros', 'rice', 'salmon', 'Sarawakese', 'scissors', 'sea[- ]bass',
            'series', 'Shavese', 'shears', 'sheep', 'siemens', 'species', 'staff', 'swine', 'traffic',
            'trousers', 'trout', 'tuna', 'us', 'Vermontese', 'Wenchowese', 'wheat', 'whiting', 'wildebeest', 'Yengeese',
        ]
    ],
];
