#==================================================================================================
# Rebet Dev Container Initialize Command (runs on the HOST before the containers are created)
#==================================================================================================
# This script prepares the shared local reverse proxy (Traefik) that routes requests to each
# Rebet application by its domain, so that multiple applications can run at the same time.
#
#  1) Create the shared docker network (if not exists).
#  2) Create the local root CA (if not exists) and a server certificate for this application.
#  3) Register the certificate to Traefik (via the file provider directory).
#  4) Start Traefik (if not running). Only one Traefik is launched for all applications.
#
# NOTE: The Traefik settings/certificates are stored in '~/.rebet/traefik' on the host, and they
#       are shared by all Rebet applications.
#
set -eu

SHARED_NETWORK_NAME="traefik-public"
TRAEFIK_CONTAINER_NAME="traefik"
TRAEFIK_IMAGE="traefik:v3"
TRAEFIK_DASHBOARD_DOMAIN="traefik.localhost"
TRAEFIK_HOME="${HOME}/.rebet/traefik"
CERTS_DIR="${TRAEFIK_HOME}/certs"
DYNAMIC_DIR="${TRAEFIK_HOME}/dynamic"
APP_CODE_NAME="{! $code_name !}"
APP_DOMAIN="{! $site_domain !}"

# Run openssl on the host if available, otherwise run it in a throwaway container.
# NOTE: Every file path given to this function must be relative to ${CERTS_DIR}.
run_openssl() {
    if command -v openssl > /dev/null 2>&1; then
        (cd "${CERTS_DIR}" && openssl "$@")
    else
        docker run --rm -v "${CERTS_DIR}:/certs" -w /certs alpine/openssl "$@"
    fi
}

# Create the local root CA if not exists.
create_root_ca() {
    if [ -f "${CERTS_DIR}/rootCA.pem" ]; then
        return
    fi
    cat > "${CERTS_DIR}/rootCA.cnf" << EOF
[req]
prompt             = no
distinguished_name = dn
x509_extensions    = v3_ca
[dn]
O  = Rebet Local Development
CN = Rebet Local Development CA
[v3_ca]
basicConstraints       = critical, CA:true
keyUsage               = critical, keyCertSign, cRLSign
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always
EOF
    run_openssl genrsa -out rootCA.key 4096
    run_openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 3650 -config rootCA.cnf -out rootCA.pem
    echo ">> Local root CA was created: ${CERTS_DIR}/rootCA.pem"
}

# Create the server certificate (signed by the local root CA) for the given domain if not exists,
# and register it to Traefik as the given name.
#
# @param $1 domain
# @param $2 name of the Traefik dynamic configuration file (without extension)
create_server_cert() {
    local domain="$1"
    local name="$2"
    if [ ! -f "${CERTS_DIR}/${domain}.crt" ]; then
        cat > "${CERTS_DIR}/${domain}.cnf" << EOF
[req]
prompt             = no
distinguished_name = dn
req_extensions     = v3_req
[dn]
O  = Rebet Local Development
CN = ${domain}
[v3_req]
basicConstraints = CA:false
keyUsage         = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName   = DNS:${domain}, DNS:*.${domain}
EOF
        run_openssl genrsa -out "${domain}.key" 2048
        run_openssl req -new -key "${domain}.key" -config "${domain}.cnf" -out "${domain}.csr"
        # NOTE: 825 days is the maximum validity period that macOS/iOS accept for TLS server certificates.
        run_openssl x509 -req -in "${domain}.csr" -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -days 825 -sha256 -extfile "${domain}.cnf" -extensions v3_req -out "${domain}.crt"
        rm -f "${CERTS_DIR}/${domain}.csr"
        echo ">> Server certificate was created: ${CERTS_DIR}/${domain}.crt"
    fi
    cat > "${DYNAMIC_DIR}/${name}.yml" << EOF
# Generated by '.devcontainer/initialize_command.sh' of Rebet application.
tls:
  certificates:
    - certFile: /etc/traefik/certs/${domain}.crt
      keyFile: /etc/traefik/certs/${domain}.key
EOF
}

echo "============================================================"
echo " Initialize For Dev Container ..."
echo "============================================================"
echo "> Create shared network '${SHARED_NETWORK_NAME}' if not exists..."
if ! docker network inspect "${SHARED_NETWORK_NAME}" > /dev/null 2>&1; then
    docker network create "${SHARED_NETWORK_NAME}"
fi
echo ">> Done."

echo "> Create certificates for '${APP_DOMAIN}' if not exists..."
mkdir -p "${CERTS_DIR}" "${DYNAMIC_DIR}"
create_root_ca
create_server_cert "${TRAEFIK_DASHBOARD_DOMAIN}" "_traefik"
create_server_cert "${APP_DOMAIN}" "${APP_CODE_NAME}"
echo ">> Done."

echo "> Start shared reverse proxy '${TRAEFIK_CONTAINER_NAME}' if not running..."
if ! docker container inspect "${TRAEFIK_CONTAINER_NAME}" > /dev/null 2>&1; then
    docker run -d \
        --name "${TRAEFIK_CONTAINER_NAME}" \
        --restart unless-stopped \
        --network "${SHARED_NETWORK_NAME}" \
        -p 80:80 \
        -p 443:443 \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        -v "${CERTS_DIR}:/etc/traefik/certs:ro" \
        -v "${DYNAMIC_DIR}:/etc/traefik/dynamic:ro" \
        --label "traefik.enable=true" \
        --label "traefik.http.routers.traefik-dashboard.rule=Host(\`${TRAEFIK_DASHBOARD_DOMAIN}\`)" \
        --label "traefik.http.routers.traefik-dashboard.entrypoints=websecure" \
        --label "traefik.http.routers.traefik-dashboard.tls=true" \
        --label "traefik.http.routers.traefik-dashboard.service=api@internal" \
        "${TRAEFIK_IMAGE}" \
        --api.dashboard=true \
        --providers.docker=true \
        --providers.docker.exposedByDefault=false \
        --providers.docker.network="${SHARED_NETWORK_NAME}" \
        --providers.file.directory=/etc/traefik/dynamic \
        --providers.file.watch=true \
        --entryPoints.web.address=:80 \
        --entryPoints.web.http.redirections.entryPoint.to=websecure \
        --entryPoints.web.http.redirections.entryPoint.scheme=https \
        --entryPoints.websecure.address=:443 \
        --entryPoints.websecure.http.tls=true
elif [ -z "$(docker ps -q --filter "name=^${TRAEFIK_CONTAINER_NAME}$" --filter "status=running")" ]; then
    docker start "${TRAEFIK_CONTAINER_NAME}"
fi
echo ">> Done."
