echo "============================================================"
echo " Set Up Dev Container ..."
echo "============================================================"

echo ""
echo "------------------------------------------------------------"
echo " Install Composer Dependencies"
echo "------------------------------------------------------------"
echo "> composer install..."
composer install -d /workspace/app
echo ">> Done."

echo ""
echo "============================================================"
echo " Dev Container Was Ready"
echo "============================================================"
echo "Please write '127.0.1.9 {! $site_domain !}' in your hosts file."
echo "And then, access below"
echo ""
echo " 1) Site Top  "
echo "     * https://{! $site_domain !}/"
echo " 2) Adminer  "
echo "     * https://{! $site_domain !}/adminer/"
echo " 3) Mailhog  "
echo "     * https://{! $site_domain !}/mailhog/"
echo " 4) SSL Add Trusted Certificate (mkcert)  "
echo "     1) Get root CA pem  "
echo "        * docker cp {! $code_name !}_devcontainer-nginx-1:/etc/mkcert/rootCA.pem ./{! $code_name !}_rootCA.pem"
echo "     2) Add trasted CA  "
echo "        * macOS  : sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain {! $code_name !}_rootCA.pem"
echo "        * Windows: certutil -addstore Root {! $code_name !}_rootCA.pem (with administrator privileges)"
echo ""
echo "NOTE: You can find this information in '/workspace/.devcontainer/post_create_command.sh'."
echo ""
