<?php

declare(strict_types=1);

namespace App\Controller;

use Rebet\Routing\Attribute\Channel;
use Rebet\Routing\Controller;

/**
 * Top Controller Class
 *
 * NOTE: This is a sample controller generated by skeleton. Edit or remove it as needed.
 */
#[Channel("web")]
class TopController extends Controller
{
    /**
     * Show the top page.
     *
     * The default view of this action is "app/resources/views/top/index.{% if $view == 'twig' %}twig{% else %}blade.php{% endif %}".
     *
     * @return \Rebet\View\View
     */
    public function index()
    {
        return $this->view()->with([
            'title'   => 'Welcome to Rebet',
            'message' => 'Your application is up and running.',
        ]);
    }
}
